modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]] #mandatory
modId="epicfight" #mandatory
version="1.0.0"
displayName="Epic Fight Mod"
logoFile="epicfight.png"
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.epicfight]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
    